### PR TITLE
put scrip inside dom-module

### PR DESCRIPTION
**Pull request by kasperpeulen**

### CODE REVIEW

**Comment by johnthad** [comment]
That's not where the &lt;script&gt; tag belongs in Polymer 1.0 (see https://www.polymer-project.org/1.0/docs/migration.html#registration).

**Comment by kasperpeulen** [comment]
@sjmiles @arthurevans  told me yesterday that they belonged inside the dom-module ...

**Comment by kasperpeulen** [comment]
@johnthad see here: https://github.com/Polymer/docs/issues/1124

**Comment by robdodson** [comment]
I think (but as always may be mistaken) that it's a style choice and the team prefers placing it inside `dom-module` to improve readability. I'm happy to merge this commit since that's what the rest of the team is trying to encourage us to do.

**Pull request merged**
